language: cpp
sudo: false
cache:
  directories:
  - container
env:
  matrix:
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" DEPLOY="1"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="latest"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Ninja" CMAKE_VERSION="3.0"
  - CMAKE_GENERATOR="Unix Makefiles" CMAKE_VERSION="latest" COVERAGE="--use-cmake-coverage"
  global:
  - secure: Pn8V9F8EsH3UB6EVXpbpzOgwHI9Kn3ItaaSEGa28z0Cy/SriLfXDFcZ7chZFGPdozXJ3PPG7hEIQGQYQfBF+2sqF677p9QmIYI7QefA8MlnugfP7yLbanSB4AGH/iyoA5F3ppBQU6SbAS/M0An51c9OglDCc9XmJdZWFSZSDB7E=
  - secure: T8DoqHSDJhSqqRQro/5PVe7BgiIR1mc164lYlbR+v45UymXanugRRvWkt/s9/gVX+l/8bdLr7IZn8dZwt2w3Zs9n9crubH9RAnP0LVGmIUbOw71IzhnGpOGqteiR5ir/aRZWmKYwmImg4NJbHtdhzBToxFp/BpPkrD8L4qrls4E=
  - secure: oD9t8yNr/G62hWDR1svq1NMIepBCHPffjYlhI5xNNnw9dcsTU46LDG4lWOirOv6pD0GBuI17Dbu+rn2crhavsSkMCs2oSCC8V7W+zlXwPzAQJ7BHJUu8KBoRPOaEmzzbHEtkp5oIyxPgVdHfJQMgP5YLCfIeHkE3NSqwaQXTWnQ=
addons:
  apt:
    sources:
    - deadsnakes
    packages:
    - python3.4-dev
install:
- eval $(curl -LSs --retry 100 --connect-timeout 3 public-travis-scripts.polysquare.org/bootstrap.py
  | python /dev/stdin -d container -s setup/conan/setup.py -e bash -p /dev/stdout
  --cmake-version ${CMAKE_VERSION})
script:
- polysquare_run check/conan/check.py ${COVERAGE} --cmake-namespace psq --generator
  "${CMAKE_GENERATOR}"
before_cache:
- polysquare_cleanup
after_success:
- polysquare_run coverage/cmake/coverage.py
before_deploy:
- polysquare_run deploy/conan/before_deploy.py --package="tooling-find-pkg-util"
deploy:
  provider: script
  skip_cleanup: true
  script: "./travis-deploy"
  on:
    repo: polysquare/tooling-find-pkg-util
    branch: master
    condition: "${DEPLOY} = 1"
